[package]
name = "dolar-rs"
version = "0.1.0"
authors = ["Andrés Testi <andres.a.testi.gmail.com>"]
edition = "2018"

[dependencies]
reqwest="0.9"
gnuplot = "0.0.31"
chrono={ version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1"

